### ISSUE TITLE
Hangs if connection to SSH host fails

### ISSUE THREAD

**Issue by davidalexisnyt** [elliotchance/sshtunnel#15]
The application hangs if the ssh.Dial() function call (first line in the forward() function) fails. The "server dial error" error is logged and the function returns, but tunnel channel is still open. Since it will now never receive anything, it just waits forever.

For now, I got it to close out by calling `tunnel.close <- struct{}{}` right after the `tunnel.logf()` call, but this is not the clean - a Panic ends up being thrown because something else is tries to close the channel, and the channel is already closed at that point.

**Comment by davidalexisnyt** [comment]
I'm using this in a program that spawns 10 - 70 goroutines to blast data into a database through an SSH tunnel. I noticed that the dial failures happen randomly - sometimes a couple of the connections would fail, somethings there is no failure. But the program hang always (and only) happens when the forward() function exits after logging the "server dial error" with any of the connections.  I wondered what would happen if I just retried the connection. So I tried this:

```
func (tunnel *SSHTunnel) forward(localConn net.Conn) {
	var (
		serverConn *ssh.Client
		err        error
		attempts   int = 10
	)

	for {
		serverConn, err = ssh.Dial("tcp", tunnel.Server.String(), tunnel.Config)
		if err == nil {
			// The connection attempt worked. We don't need to retry anymore.
			break
		}

		attempts--
		time.Sleep(100 * time.Millisecond)

		if attempts == 0 {
			tunnel.logf("server dial error: %+v, [%d]", err, attempts)
			return
		}
	}
. . .
```

This works beautifully! The connections succeed after only 1 or 2 retries, my program does it's thing, and it exits normally at the end.

Not sure if this is a good approach, but it works.

**Comment by elliotchance** [comment]
I think this is a fine solution. I'm happy to accept a PR if you want this to be a feature of the library itself.

**Comment by davidalexisnyt** [comment]
Nice!  Thanks. Created a PR: https://github.com/elliotchance/sshtunnel/pull/16
